name: flutter_embedded_meilisearch
description: >
  An embedded instance of the engine that powers Meilisearch (milli).
  Enables easy, blazingly fast, client-side full-text search in Flutter.
version: 0.0.0
homepage: https://github.com/GregoryConrad/embedded_meilisearch
repository: https://github.com/GregoryConrad/embedded_meilisearch

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  embedded_meilisearch: ^0.0.0
  path: ^1.8.2
  path_provider: ^2.0.11

dependency_overrides:
  embedded_meilisearch:
    path: ../embedded_meilisearch

dev_dependencies:
  analyzer: ^4.6.0
  flutter_test:
    sdk: flutter