[package]
name = "embedded_milli"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.49.1"

[dependencies]
lazy_static = "1.4.0"
flutter_rust_bridge = "1.49.1"
anyhow = "1.0.66"
serde = "1.0.147"
serde_json = "1.0.87"
milli = { path = "milli/milli" }
