version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/embedded_meilisearch/native"
    schedule:
      interval: weekly