version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    versioning-strategy: increase # https://github.com/dependabot/dependabot-core/issues/6446
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
