name: embedded_meilisearch
description: >
  An embedded instance of the engine that powers Meilisearch (milli).
  Enables easy, blazingly fast, client-side full-text search in Dart.
version: 0.0.0
homepage: https://github.com/GregoryConrad/embedded_meilisearch
repository: https://github.com/GregoryConrad/embedded_meilisearch

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.49.0

dev_dependencies:
  analyzer: ^5.2.0
  ffigen: ^6.1.2
  test: ^1.22.0
