name: embedded_meilisearch
description: >
  An embedded instance of the engine that powers Meilisearch (milli).
  Enables easy, blazingly fast, client-side full-text search in Dart.
version: 0.0.0
homepage: https://github.com/GregoryConrad/embedded_meilisearch
repository: https://github.com/GregoryConrad/embedded_meilisearch

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

dev_dependencies:
  analyzer: ^4.6.0
  test: ^1.16.0