name: flutter_mimir
description: >
  An embedded instance of the engine that powers Meilisearch (milli).
  Enables easy, blazingly fast, client-side full-text search in Flutter.
version: 0.0.0
homepage: https://github.com/GregoryConrad/mimir
repository: https://github.com/GregoryConrad/mimir

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mimir: ^0.0.0
  path: ^1.8.2
  path_provider: ^2.0.11

dependency_overrides:
  mimir:
    path: ../mimir

dev_dependencies:
  analyzer: ^5.2.0
  flutter_test:
    sdk: flutter
